config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # get 'welcome/index'
  root 'welcome#index'
  get 'mailbox/inbox'=>"mailbox#inbox",as: "mailbox_inbox"
  get 'mailbox/sent'=>"mailbox#sent",as: "mailbox_sent"
  get 'mailbox/trash'=>"mailbox#trash",as: "mailbox_trash"

  resources :conversations do
    member do
      post :reply
      post :trash
      post :untrash
    end
  end
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :validatable

  acts_as_messageable

  def mailboxer_name
    self.name
  end

  def mailboxer_email(object)
    self.email
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  helper_method :mailbox
  helper_method :conversation 

  private
  def mailbox
    @mailbox ||= current_user.mailbox
  end

  def conversation
    @conversation ||= mailbox.conversations.find(params[:id]) if params[:id]
  end

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up,keys: [:name,:email,:password,:password_confirmation])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name,:email,:password,:password_confirmation,:current_password])
  end
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  before_action :authenticate_user!

  def new
  end

  def create
    recipients = User.where(id:conversation_params[:recipients])
    conversation = current_user.send_message(recipients,conversation_params[:body],
      conversation_params[:subject]).conversation
    flash[:success] = "Your message was successfully sent"
    redirect_to conversation_path(conversation)
  end

  def show
    @receipts = conversation.receipts_for(current_user)
    conversation.mark_as_read(current_user)
  end

  def reply
    current_user.reply_to_conversation(conversation,message_params[:body])
    flash[:success] = "Your reply was successfully sent"
    redirect_to conversation_path(conversation)
  end

  def trash
    conversation.move_to_trash(current_user)
    redirect_to mailbox_inbox_path
  end

  def untrash
    conversation.untrash(current_user)
    redirect_to mailbox_inbox_path
  end

  private
  def conversation_params
    params.require(:conversation).permit(:body,:subject,recipients:[])
  end

  def message_params
    params.require(:message).permit(:body,:subject)
  end

end

app/controllers/mailbox_controller.rb
class MailboxController < ApplicationController
  before_action :authenticate_user!
  def inbox
    @inbox = mailbox.inbox
    @active = :inbox
  end

  def sent
    @sent = mailbox.sentbox
    @active = :sent
  end

  def trash
    @trash = mailbox.trash
    @active = :trash
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
    case level.to_sym
      when :notice then "alert alert-success"
      when :info then "alert alert-info"
      when :alert then "alert alert-danger"
      when :warning then "alert alert-warning"
    end
  end

  def active_page(active_page)
    @active == active_page ? "active": ""
  end

  def unread_messages_count
    mailbox.inbox(:unread=>true).count(:id)
  end
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/helpers/mailbox_helper.rb
module MailboxHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/conversations/_conversation.html.erb
<div class="media">
  <div class="media-body">
    <div class="media-heading">
      <%= conversation.originator.name %><br/>
      <small>Subject<%= conversation.subject %></small>
      <small>Date<%= conversation.messages.last.created_at.strftime("%A, %b %d,%Y at %I:%M%p") %></small>
    </div>
    <%= truncate conversation.messages.last.body, length:145 %>
    <%= link_to "View",conversation_path(conversation) %>
  </div>
</div>

app/views/conversations/_form.html.erb
<%= form_for :conversation,url: :conversations, html: {class: ""} do |f| %>
   <div class="form-group">
      <%= f.label :recipients %>
      <%= f.select(:recipients, User.all.collect {|p| [ p.name, p.id ] }, {}, { multiple: true , class: "form-control" })%>
    </div>
  <div class="form-group">
    <%= f.label :subject %>
    <%= f.text_field :subject, placeholder: "Subject", class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :message %>
    <%= f.text_area :body, placeholder: "type your message", class: 'form-control' %>
  </div>
  <%= f.submit "Send Message", class: 'btn btn-success' %>
<% end %>

app/views/conversations/_messages.html.erb
<% @receipts.each do |receipt| %>
  <% message = receipt.message %>
  <div class="media">
    <div class="media-body">
      <div class="media-heading">
        <%= message.sender.name %><br/>
        <small>Subject:<%= message.subject %></small>
        <small>Date:<%= message.created_at.strftime("%A, %b %d, %Y at %I:%M%p") %></small>
      </div>
      <%= message.body %>
    </div>
  </div>
<% end %>

app/views/conversations/new.html.erb
<%= render partial: 'mailbox/folder_view', locals: {is_conversation: true} %>

app/views/conversations/show.html.erb
<div class="row">
    <div class="spacer"></div>
    <div class="col-md-6">
      <%= link_to "Compose",new_conversation_path,class: 'btn btn-success' %>
    </div>
    <div class="col-md-6 text-right">
      <% if conversation.is_trashed?(current_user) %>
        <%= link_to "Untrash",untrash_conversation_path(conversation),method: :post,
          class: 'btn btn-info' %>
      <% else %>
      <%= link_to "Move to trash",trash_conversation_path(conversation),method: :post,
        class: 'btn btn-danger' %>
      <% end %>
    </div>
    <div class="spacer"></div>
  <div class="col-md-4">
    <div class="panel panel-default">
      <div class="panel-body">
        <%= render partial:"mailbox/folders" %>
      </div>
    </div>
  </div>
  <div class="col-md-8">
    <div class="panel panel-default">
      <div class="panel panel-body">
        <%= render partial: "messages" %>
      </div>
      <div class="panel-footer">
        <%= form_for :message,url: reply_conversation_path(conversation) do |f| %>
          <div class="form-group">
            <%= f.label :reply %>
            <%= f.text_area :body, placeholder: "Reply",rows: 4,class: 'form-control' %>
          </div>
          <%= f.submit "Reply", class: 'btn btn-success' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Messenger',root_path, class: 'navbar-brand' %>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav pull-right">
        <% if user_signed_in? %>
           <li><%= link_to "Hello, #{current_user.name}", "#" %></li>
           <li><%= link_to "Inbox",mailbox_inbox_path %></li>
          <li><%= link_to "Log Out",destroy_user_session_path,method: :delete %></li>
        <% else %>
          <li class="active"><%= link_to "Login",new_user_session_path %></li>
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Messenger</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag "//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/nav' %>
    <% flash.each do |key,value| %>
      <div class="text-center alert-info">
        <%= value %>
      </div>
    <% end %>
    <div class="container main-container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/mailbox/_folder_view.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="spacer"></div>
    <%= link_to "Compose",new_conversation_path,class: 'btn btn-success' %>
    <div class="spacer"></div>
  </div>
  <div class="col-md-4">
    <div class="panel panel-default">
      <div class="panel-body">
        <%= render partial: "mailbox/folders" %>
      </div>
    </div>
  </div>
  <div class="col-md-8">
    <div class="panel panel-default">
      <div class="panel-body">
        <% if is_conversation %>
          <%= render 'conversations/form' %>
        <% else %>
          <%= render partial: 'conversations/conversation', collection: messages %>
        <% end %>
    </div>
  </div>
</div>

app/views/mailbox/_folders.html.erb
<ul class="nav nav-pills nav-stacked">
  <li class="<%= active_page(:inbox) %>">
    <%= link_to mailbox_inbox_path do %>
      <span class="label label-danger pull-right"><%= unread_messages_count %></span>
      <em class="fa fa-inbox fa-lg"></em>
      <span>Inbox</span>
    <% end %>
  </li>
  <li class="<%= active_page(:sent) %>"> 
    <%= link_to mailbox_sent_path do %>
      <em class="fa fa-paper-plane-o fa-lg"></em>
      <span>Sent</span>
    <% end %>
  </li>
  <li class="<%= active_page(:trash) %>">
    <%= link_to mailbox_trash_path do %>
      <em class="fa fa-trash-o fa-lg"></em>
      <span>Trash</span>
    <% end %>
  </li>
</ul>

app/views/mailbox/inbox.html.erb
<%= render partial: 'mailbox/folder_view', locals: {is_conversation: false, messages: @inbox} %>

app/views/mailbox/sent.html.erb
<%= render partial: 'mailbox/folder_view', locals: {is_conversation: false, messages: @sent} %>

app/views/mailbox/trash.html.erb
<%= render partial: 'mailbox/folder_view', locals: {is_conversation: false,messages: @trash} %>